### PR TITLE
Fix import paths

### PR DESCRIPTION
**Pull request by johto**
Congratulations on your renaming.  Here's a patch to fix the import paths.  I hope you find it satisfactory.

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
Thanks for the patch! This will break others using it under the old name, right? I believe GitHub docs on the rename implied old links would be redirected which should work with `go get` I think. But anyone coming here now is going to be very confused at best, so the rename makes sense.

**Comment by johto** [comment]
> This will break others using it under the old name, right? I believe GitHub docs on the rename implied old links would be redirected which should work with go get I think.

Oh, I didn't know such redirection was in place.  I just tested it, and yeah, this would break for people using that URL.

I guess the other option would be to try and redirect everyone to the old URL.  Looks like Go 1.4 at least has [canonical import paths](https://golang.org/doc/go1.4#canonicalimports).

I feel like it would be better to just break existing users right now, but I'll leave the decision up to you.

**Comment by uhoh-itsmaciek** [comment]
No, I think breaking changes at this point in the library's life cycle are totally reasonable. I just wanted to make sure I was doing it knowingly.

**Comment by uhoh-itsmaciek** [comment]
Thanks!

**Pull request merged**
