### PR TITLE
Support the clean way of rejecting SSL connections

### PR DESCRIPTION
**Pull request by johto**
I'm working on a project which would be much better if there was a way to cleanly reject SSL connections.  Here's one way we could implement it.  I tried not to lock out too many options for people implementing their own extensions on top of the PG protocol.  This coding supports arbitrary startup-phase packets, so long as they're at least 8 bytes in length (i.e. they have the same kind of magic identifier all PG's packets have), and they don't take the connection out of the startup sequence.  I think those assumptions are fairly reasonable.

This still needs a bit of cleanup, but any thoughts on the general approach?  The pattern would be roughly:

```
	for {
		err = c.stream.Next(&message)
		if err != nil {
			// ...
		}
		if fbproto.IsStartupMessage(&message) {
			break
		} else if fbproto.IsSSLRequest(&message) {
			err = c.stream.WriteSSLRequestResponse('N')
			if err != nil {
				// ...
			}
		} else {
			// unknown startup message; could handle e.g. CancelRequest here
		}
	}
	_, err = fbproto.ReadStartupMessage(&message)
	if err != nil {
		// ...
	}
```

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
Nice, I like this a lot. I think it's a pretty reasonable mechanism overall. I don't like the opaque byte argument to `WriteSSLRequestResponse`, but that's minor. Maybe just separate `AccedeSSL` and `DeclineSSL` methods? That makes extension difficult, but between yes and no, we kind of cover all bases. Or if not, we should make it consistent with `Send`, so maybe `SendSSLRequestResponse` with constants for the `S` and `N` magic bytes.

**Comment by johto** [comment]
> Nice, I like this a lot. I think it's a pretty reasonable mechanism overall.

Great!

> I don't like the opaque byte argument to WriteSSLRequestResponse, but that's minor. Maybe just separate AccedeSSL and DeclineSSL methods? That makes extension difficult, but between yes and no, we kind of cover all bases.

I thought of having two methods first, but I felt like that might unnecessarily limit people who have their own extensions on top of the protocol.

> Or if not, we should make it consistent with Send, so maybe SendSSLRequestResponse

Good point, will change.

> with constants for the S and N magic bytes.

Yeah, I think this is a better way to make the argument less magic, since it still leaves the options open.

I'll change the PR.

**Comment by johto** [comment]
I've pushed an updated version.  Any thoughts?

**Comment by johto** [comment]
Hmm.  I didn't notice before, but this actually breaks the frontend stream functionality.  It looks like *Message.Force doesn't correctly deal with a partially read message.  Perhaps I'm misunderstanding something, but shouldn't it be reading from `m.union` instead of `m.future`?  Everything appears to work once I do this:

```
diff --git a/core/framing.go b/core/framing.go
index 0b80060..60ad12e 100644
--- a/core/framing.go
+++ b/core/framing.go
@@ -56,7 +56,7 @@ func (m *Message) Force() ([]byte, error) {
    }
 
    payload := buf[:payloadSz]
-   _, err := io.ReadFull(m.future, payload)
+   _, err := io.ReadFull(m.union, payload)
 
    m.buffered.InitReader(payload)
    m.future = nil
```

**Comment by uhoh-itsmaciek** [comment]
Thanks for the update. Busy week, but I'll take a look at it this weekend.

Re: `Force()`, I have no idea, actually. I'll take a look, but I believe @fdr did most of that particular code--@fdr, do you know about this?

**Comment by fdr** [comment]
That looks fine. As you both have probably surmised, the point is to tell femebe to materialize an entire message in memory, which is useful for some workloads.

**Comment by fdr** [comment]
In particular, so the `.Bytes()` returns a complete message.

**Comment by johto** [comment]
> That looks fine. As you both have probably surmised, the point is to tell femebe to materialize an entire message in memory, which is useful for some workloads.

Right.  I think there's a better way to write that function.  I'll open a separate PR for it.  Thanks for your input.

**Comment by uhoh-itsmaciek** [comment]
Ok, I think I'm pretty happy with this. Merging. Thanks!

**Comment by uhoh-itsmaciek** [comment]
Rebased and merged.

**Pull request closed without merging**
